output "vpc_id"                  { value = aws_vpc.main.id }
output "vpc_cidr"                { value = aws_vpc.main.cidr_block }
output "public_subnet_a_id"      { value = aws_subnet.public_a.id }
output "public_subnet_b_id"      { value = aws_subnet.public_b.id }
output "private_app_subnet_a_id" { value = aws_subnet.private_app_a.id }
output "private_app_subnet_b_id" { value = aws_subnet.private_app_b.id }
output "private_db_subnet_a_id"  { value = aws_subnet.private_db_a.id }
output "private_db_subnet_b_id"  { value = aws_subnet.private_db_b.id }
output "public_subnet_ids"       { value = [aws_subnet.public_a.id, aws_subnet.public_b.id] }
output "private_app_subnet_ids"  { value = [aws_subnet.private_app_a.id, aws_subnet.private_app_b.id] }
output "private_db_subnet_ids"   { value = [aws_subnet.private_db_a.id, aws_subnet.private_db_b.id] }
output "internet_gateway_id"     { value = aws_internet_gateway.main.id }
output "nat_gateway_a_id"        { value = aws_nat_gateway.nat_a.id }
output "nat_gateway_b_id"        { value = aws_nat_gateway.nat_b.id }